name: Deploy to Production

on:
  push:
    branches: [ master ]  # Change to your main branch name (e.g., master, main, production)

jobs:
  deploy-client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Use your Node.js version
      - name: Install Dependencies
        run: |
          cd client
          npm ci
        continue-on-error: false
          
      - name: Build React App
        run: |
          cd client
          npm run build
        continue-on-error: false
        
      - name: Debug Build Output
        run: |
          ls -la client/build || echo "Build directory not found"
          
      - name: Test SSH Connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "SSH connection successful"
            whoami
            pwd
            ls -la /var/www || echo "Directory /var/www not found"
            mkdir -p /var/www/yabellobingo || echo "Failed to create directory"
            
      - name: Deploy to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "client/build/"
          target: "/var/yabellobingo"  # Nginx web root directory
          strip_components: 2  # Removes 'client/build/' from the path
          
  deploy-server:
    runs-on: ubuntu-latest
    needs: deploy-client  # Run after client deployment
    steps:
      - uses: actions/checkout@v2

      - name: Deploy Server Files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "server/"
          target: "/root/yabello1/server"  # Server directory for root user
          
      - name: Restart Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/yabello1/server
            # Source profile to ensure environment variables are loaded
            source /root/.bashrc || true
            # Try to find npm and pm2 in various locations
            export PATH="$PATH:/usr/bin:/usr/local/bin:/root/.nvm/versions/node/*/bin:/usr/local/nodejs/bin"
            # Check if node and npm are available
            which node || echo "Node not found in PATH"
            which npm || echo "npm not found in PATH"
            which pm2 || echo "pm2 not found in PATH"
            # Install dependencies using available npm
            if command -v npm &> /dev/null; then
              npm ci --production
            else
              echo "npm not found, skipping dependency installation"
            fi
            # Restart server using available pm2
            if command -v pm2 &> /dev/null; then
              pm2 restart yabello-server || pm2 start server.js --name yabello-server
            else
              echo "pm2 not found, skipping server restart"
              # Try to install pm2 globally
              if command -v npm &> /dev/null; then
                npm install -g pm2
                pm2 restart yabello-server || pm2 start server.js --name yabello-server
              fi
            fi
